graph LR
    subgraph s1["查询执行分支"]
        H2["查询标准化处理"]
        H1["执行查询"]
        J1["CTE解析识别"]
        K1["CTE结果共享缓存"]
        L1["返回查询结果"]
    end
    subgraph s2["直接执行分支"]
        M1["查询计划分析"]
        D1["直接执行查询"]
        M2["参数化查询处理"]
        O1{"是否缓存"}
    end
    H1 --> H2
    H2 --> J1
    J1 --> K1
    K1 --> L1
    D1 --> M1
    M1 --> M2
    M2 -->  O1
    O1 -- 是 --> H2
    O1 -- 否 --> L1

    style J1 fill:#e3f2fd
    style M2 fill:#e8f5e8