xychart-beta
    title "执行时间对比 (毫秒)"
    x-axis ["simple_count", "simple_sum", "simple_avg", "simple_minmax", "medium_group", "medium_join", "medium_window", "medium_distinct", "complex_analytics", "complex_subquery", "complex_cte", "complex_joins"]
    y-axis "执行时间 (ms)" 0 --> 35
    bar [23.06, 23.50, 24.54, 23.02, 27.52, 25.16, 26.11, 27.11, 30.37, 28.80, 26.80, 25.34]
    bar [21.41, 21.83, 20.25, 21.39, 22.43, 21.27, 21.35, 22.53, 21.98, 21.00, 21.50, 21.58]