xychart-beta
    x-axis ["简单聚合查询", "多表连接查询", "复杂分析查询", "窗口函数查询"]
    y-axis "执行时间(ms)" 0 --> 7
    bar "10次测试" [0.33, 1.33, 6.11, 1.33]
    bar "50次测试" [0.30, 1.33, 5.81, 1.92]
    bar "100次测试" [0.29, 1.33, 5.03, 1.45]
    bar "200次测试" [0.30, 1.87, 5.10, 1.44]